ytfzf

If a Youtube video is started in the Audio-Only mode (`-m`), and then aborted with Ctr-C, the Video starts to play because the "else" branch is taken as of the return code being non-zero. I added a check if the return code is equal to 4 (The return value of MPV if the media stream is canceled with Ctr-C) to prevent that. There is probably a much cleaner way to do this ;-)

Audio-Only Bug if aborted with Ctr-C

---

ytfzf

Added a new flag `-L` to use ytfzf as search tool, the youtube URL of the selected link will be printed out to stdout. I didn't go through all of the code so I may have missed something.
Edit: This doesn't work together with downloading thumbnails.

Add flag to use ytfzf as yt-search

---

README.md
ytfzf

The support for macOS had been somewhat implemented in #17 but when testing it, it turned out that it did not work.
In this PR, I have created a function called `sed` which automatically decides which `sed` command to use depending on the user's OS.
Let me know if any changes needed to be made in this PR :)

Added better macOS support

---

ytfzf

stty errors go to /dev/null and if it fails gives an error message about stdin because stty seems to only fail when stdin is given and - is not given for a search query

added error message when stdin is used and -  is not provided

---

README.md

Fix typo "ueberzup" to "ueberzug"

---

ytfzf

If there's a dependency missing, I don't think there's any reason to create functions and do a bunch of operations before reporting it with a crash. The CPU time and the memory footprint are minor, but it's just good practice if the crash happens before all the functions and other things are defined. Also, I think putting a `[OPTIONS]` indicator in the help screen would be nice. Many programs have it (for example, kitty, python, gcc) and it makes things clearer (where to put the flags, where to put args). Explicit is better than implicit, after all.
It's also conventional to use hyphens or underscores instead of spaces in indicators like `search-query`.
These are just suggestions. Please feel free to edit as you see fit, or close the PR if inappropriate.

Exit earlier if dependency missing

---

ytfzf

Reverting a change I made in [PR#58](https://github.com/pystardust/ytfzf/pull/58) which incorrectly causes crashes when `YTFZF_PLAYER` has multiple words.
It'd still be nice to have a better `dep_ck` function so that mpv wouldn't be a hard dependency. It isn't, really, and one could probably use VLC or some other player to the same effect.

Revert change to dep_ck function

---

README.md
ytfzf

This doesn't necessarily need to be merged but, I feel making a way for longopts to be used would be good and this was the easiest way to implement that (that i found)
I tried just parsing the options manually but it resulted in some funky behavior with the regular search query input so i scrapped it. It might be possible to do it, I just don't know how
Printf "Option not found" is removed because getopts already does that, but since getopts doesn't have default support for long opts, I added an error message similar to getopts' when an invalid longopt is used

Option parsing refactor

---

README.md

I wrote a small ebuild to install ytfzf and maintain its dependencies on Gentoo. The ebuild is available in nitratesky overlay.

Added Gentoo installation instructions

---

Makefile

According to Arch Package Guidlines: https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_etiquette
> Packages should never be installed to /usr/local/
I would like to use makefile in AUR's PKGBUILD

change install location to /usr/bin

---

Makefile

>Hey guys, Im running into some problems with installing ytfzf:
```
chmod 755 ytfzf
mkdir -p /usr/bin
install ytfzf /usr/bin/ytfzf
install: /usr/bin/ytfzf: Read-only file system
make: *** [install] Error 71
```
> Is someone able to help me out on this one?
Apparently on mac, the install location needs to be /usr/local/bin

change install loc, depending on OS

---

ytfzf

* got rid of excess longopts for -r,
* each option that can be turned on off  has a longopt equivelent
* this may seem useless, but it's very useful if you have something set in config, and want to turn it off once
* eg:
```sh
#config 
search_again=1
```
`ytfzf --search=0 search`

long-options enable/disable

---

docs/conf.sh
ytfzf

This might be desirable for example if a user wants to use a folder on a
tmpfs filesystem to cache thumbnails.
Thx a lot for sharing your awesome script by the way ! :+1:

enable `thumb_dir` to be relocated via `conf.sh`

---

ytfzf

The output of `type` is localized.  For example, `function` in German is
`Funktion`,  which makes the `grep` statement return false when it actu-
ally should return true.
`LANG=C` unifies this.

fix preview text on alien locales

---

README.md
docs/conf.sh
ytfzf

* Subscriptions
* subscriptions can be set with $subscriptions_file (~/.config/ytfzf/subscriptions by default)
* a subscription is a link to a channel's video page, eg: https://www.youtube.com/user/PewDiePie/videos (see README)
* multiple urls for input
* channel name, views, etc... has color when using -t
* not using - for stdin gives error code of 2 instead of 1
* --version now bolds each module, and prints the version of fzf if installed
* when reading from an external menu, ytfzf threw an error when it shouldn't have
* if -t was given, it didn't check if fzf was installed, it will now
* when -tD was given, it would switch to use fzf, instead it warns about external menus not having thumbnail support then continues
* history_file and current_file didn't work in conf.sh
* issue with tac …

Development merge 1.1.0

---

README.md
docs/INSTALL.md
docs/USAGE.md

I have shortened the README.md file by creating new files that you can access easily from the table of content. I personally think this is a much better implementation. Now we can actually add and change the README file a bit more and avoid getting a huge README which is kind of hard to read

Separation

---

docs/conf.sh
ytfzf

- Add enable_noti=<1:default, 2> config that enable notification feature
- Add flag -N --notification <0,1> enable/disable notification feature
- Add notification flag -h entry
- If enable notification & thumbnails it will use thumbnail as notification icon else it will use default thumbnail icon (user defined) file at ./config/ytfzf/default_thumb.png
- Fix zsh complain syntax at download_thumbnails

fix+feat: add --notification= option, fix zsh complain syntax

---

ytfzf

The format selection menu was too cluttered also the video only options were giving me trouble. So I changed some lines in script for myself then I thought maybe other people are having the same problems therefore I am creating this pull request.
Basically it only shows Video resolutions that are available eg. 144p,480p just like in Youtube and with an audio only option . So user can just select the resolution and be done with it.

[Proposal] Changing the video format menu.

---

ytfzf

This patch adds the `-L` (Follow redirects) flag to the curl command in `get_video_data()` to *bypass* the Youtube consent page shown in some countries. The issue would occur when trying to scrape data from Youtube.
Tested and seems to work well.
This is a followup to https://github.com/pystardust/ytfzf/pull/187 where it was suggested to try this approach instead of using wget with the `--no-cookie` flag set.
(Also see #183 )

Youtube consent bypass

---

ytfzf

I made a mistake in original commit, I left the 'P' for 720p capitalized in quality variable under get_video_format function. That caused bugs when 720p video was being selected. I fixed that and removed unnecessary code.

 [FIX} Fixed get_video_format function for 720p videos.

---

ytfzf

Menu got messed up if live videos were selected. I made the video quality list completely dependent on the youtube-dl output not just the max quality like before. Formatting is still the same.

[Fix] Changed the way format menu is implemented.

---

docs/conf.sh
ytfzf

this pull request adds many event functions that act similarly to on_parse_opt
it also adds customizable sorting methods
* `custom_videos_data`
*  when videos_data is provided in a user defined function this should also be set to 1 so that ytfzf doesn't override videos_data
gets called when a video is selected
this function handles sending the notification
**usage**:
* custom notifications
gets called after `videos_data` is set in `scrape_yt` and `scrape_channel`
there is no expectation of what this function does,
**parameters**:
1. `videos_data`
2. `videos_json`
3. `yt_json`
**usage**:
* to do stuff with videos_data, eg write it to a file,
* make a custom videos_data menu with videos_json/yt_json
gets called when the search is gotten
there is no expectation of what this function does …

feat: event functions

---

ytfzf

when ext_menu is enabled notify-send should always be used if possible for warnings/errors

fix: notify-send errors with ext_menu if possible

---

docs/INSTALL.md
ytfzf

1. remove `shuf` dependency, and avoid `sort -R` because it's not posix
2. set default args for bad_opt_arg to reduce code duplication
in `preview_img` `args` is set because `${*}` and `${@}` are not posix,
I found this information with [`shellcheck`](https://github.com/koalaman/shellcheck)
wikipedia also has nice tables on programs like `sort` that shows which versions have what args

Code improvements

---

docs/conf.sh
ytfzf

if anything else requires the disabling of printing to stdout, we only have to add it to print_info

feat: silent mode

---

docs/conf.sh
ytfzf

This adds a new feature to save the search/query history and a corresponding fzf menu to select old searches.
New flags:
- `ytfzf -q` Open search history menu
- `ytfz -X` Clear search history menu
New Options:
- `enable_search_hist=1` Enable search history saving 
- `enable_search_history_menu=1` Auto use the search history menu
The fzf query will be used with `alt-enter` or if no other selection left, so can be used as an alternative to regular search input.
Also works with looping :D

feat: Add search history and a search history menu

---

docs/conf.sh
ytfzf

Not sure why this was missing, but this adds the `is_download` config option.

fix: Add missing is_download config option

---

ytfzf

This pr adds a scrape function for urls to get their video data and save it to watch history.
I am using `youtube-dl -J` to get the video json, however the data it returns is not in the same format as the other scrapers (e.g. duration in seconds instead of HH:MM:SS), this however does not seem to affect the functionality.
NOTE: everything works when `sort_videos_data` is disabled, however there seems to be a bug in the `sort_video_data_fn` function where the first line does not get returned.
This bug effects the other functions of ytfzf as well, such as the first result of `scrape_yt` gets removed.

Url watch history

---

ytfzf

Ignores the date and time and only uses title to compare search history

Fix: remove duplicate search history based on title

---

docs/conf.sh
ytfzf

This PR ads a new option `enable_persistent=1` which launches `ytfzf` in persistent mode, in this mode the fzf --bind option is used to execute and open the player without exiting fzf.
This has the advantage of:
- no looping, fzf will just persist
- unlike looping, the pointer will stay at the last position (far less annoying)

Add a persistent mode

---

ytfzf

This PR fixes a bug, it stops persistent key binds from removing keys from `key_binds` which are needed in `handle_key_binds`

Fix: stop removing key binds

---

ytfzf

having more information for `-t` is good. all positions are the same, so the method for getting the date still works.

feat: customizeable sort

---

ytfzf

The unquoted variables caused an error with the `-t` option if there was a whitespace in the search query. Quoting them fixes it.
```
$ ytfzf -t "naruto amv"
Scraping site...
Fetching thumbnails...
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --  2439k     0    29     0     0  0:00:01  0:00:01 --:--:-- 1602k
unknown option: amv-43818/videos_json'
```

Fix error with --show-thumbnails option

---

docs/man/ytfzf.1
docs/man/ytfzf.5
ytfzf

1. `ytdl-opts`: For passing command-line options to youtube-dl
> ```
> ytfzf -d --ytdl-opts='-o ~/Videos/%(title)s.%(ext)s'
> ytfzf -d --ytdl-opts='--config-location ~/.config/youtube-dl/alt-config'
> ```
2. `ytdl-path`: For using a fork of youtube-dl
> ```
> ytfzf -d --ytdl-path=yt-dlp
> ```
Though these options can already be set by defining  the `downloader` function, this might make it easier for users who aren't familiar with shell scripting.

feat: New options `ytdl-opts` and `ytdl-path`

---

docs/man/ytfzf.1
docs/man/ytfzf.5
ytfzf

Add a `--force-youtube` option to convert the invidious links to youtube links before playing/downloading while still using invidious for scraping.
This might be good for some uses such as scripting with the `-L` flag or if the invidious instances are too slow.
(edit: I amended the commit to add 'www' to the youtube url and `/g` to the sed command.)

feat: Add option to convert invidious to yt links

---

docs/INSTALL.md
ytfzf

I changed the shell script to use yt-dlp due to youtube-dl being slow to the point of being unusable. yt-dlp is actively maintained and works much better.
I also updated the install makefile dependencies to use yt-dlp, and for the arch-based switches out youtube-dl with yt-dlp.
Nothing else in it is changed though due to me not knowing much about other distros and their packaging.

switch to yt-dlp and change the arch install deps

---

docs/man/ytfzf.1
docs/man/ytfzf.5
ytfzf

Tried this and it works great on both x11 and wayland (it's non-generic but it's still something for #64)
Prefer this over ueberzug on x11 as well given the image will work properly when switching terminal tabs.
I've seen mentions of using `transfer-mode file` with fzf and not having a separate --clear, but it displayed nothing if I did either of these. Not that I know kitty/icat that well so there may be something to improve.

feat: add kitty/icat thumbnail viewer support

---

addons/scrapers/ard

This is a scraper for the media library from the german broadcast service [ARD](https://www.ardmediathek.de/).
- scrapes the API from [ARD](https://www.ardmediathek.de/) and get the video link
- thumbnail fetching
- respects thumbnail resolution choice
- `--pages` flag is supported. It is implemented as a multiplication of the default page size. This avoids making multiple connections.
- `alt-p` to search for next page
With the default video player, it opens only the audio. With following function in `conf.sh` it opens the video for me
```sh
video_player () {
mpv "$@"
}
```
Basic example:
```sh
ytfzf -c ard tagesschau
```
Example with amount of pages:
```sh
ytfzf -c ard --pages=3 sport
```
The `pad_left` function is copied from the [source code of …

feat: ard scraper

---

ytfzf

1. Fixed displaying details of video with title containing quotes - when parsing JSON string object to text, current approach is to find first two quotes in the object; this PR assumes that closing quote is the last one in parsed line, using the fact that sed's `*` matches greedily
2. Fixed displaying escaped backslashes in search results - jq's `@tsv` filter escapes backslashes, which is not necessary here; alternative that does not do that is `join("\t")`
3. Fixed issues with videos that occur multiple times in search results due to paging (repeated details, thumbnail preview not updating)
- note that this PR removes `unique_by(.ID)` filter as I do not see any reason to leave it (after filtering by URL we can assume that objects left are equal), but it can be restored if I am mistaken …

Fixes related to displaying video data

---

ytfzf

vid.puffyan.us is down, y.com.sb works fine for me..

changed the individous_instance

---

ytfzf

If you want to have a multiline string anywhere in your environment such as
```shell
export FZF_DEFAULT_OPTS='--border
--bind "ctrl-y:execute-silent(echo {} | xclip)+abort"
--preview "(pistol {}) 2> /dev/null | head -500"'
```
`ytfzf` will error with
```
/usr/bin/ytfzf: line 488: export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```
because it is trying to `export`  `--bind`
(I realize I could put it all on one line but it looks neater in my zshrc this way and it works with fzf just fine) :stuck_out_tongue: 
This change set tells `env` to delimit variable definitions by the special unix null character, by calling it with `-0`. This character is much less likely to be found in an env var as it denotes the end of a string.
stuff I searched to come to …

Allow for multiline env vars when generating and reading /tmp/ytfzf-env

---

credits/bsgalvan.md
docs/man/ytfzf.1
ytfzf

Should fix #570.
Quick and dirty implementation of the process explained in the issue above.
I am not well versed with `jq`, so this might be a roundabout manner of doing what needs to be done!
~TODO: need to implement logic for staleness of the cached instance list.~

feat: use invidious api to get healthy instances

---

docs/man/ytfzf.1
docs/man/ytfzf.5

Follows fix spelling in the manual files according to the packaging in Debian, because I am the maintainer of the package in Debian.

Fix spelling in manpages.

---

Makefile
ytfzf

Follows improve Makefile for better compatibility with other systems. Patch according to Debian packaging, because I am the maintainer of the package in Debian.

Improve makefile

---

Makefile
README.md

I noticed in the README, we are encouraging users to include the docs by default.
I also noticed the makefile had an empty `all` target. GNU `make`, when invoked without an explicit target, will snag the first one it finds.
This PR simply adds the default `install` and `doc` targets the default. I updated the README to reflect this as well.

Make the Makefile 'all' target phony and default

---

.github/ISSUE_TEMPLATE/bug_report.md
Makefile
ytfzf

I noticed the Vim modeline was not working. I checked all my settings locally and sure enough, it wasn't being picked up because of a single space after the comment `#`. 
According to [the docs for Vim modelines](https://vimdoc.sourceforge.net/htmldoc/options.html#modeline), the space following `vim:` is optional, but the one preceding it is not. This should ensure proper detection.
This PR adds not only the required space, but goes ONE STEP FURTHER, and adds an *optional* one following the colon. This is avandt-garde code styling, I KNOW. FWIW the help doc provides an example of each, with and without the trailing space after the colon.
Additionally, modelines are a known security vulnerability. Consider removing it to protect users running a version less than `8.1.1365`.  A lot of …

Add required whitespace to vim modeline

---

Makefile
ytfzf

I went through with a fine tooth regex comb and manually fixed all the comments that that did not have a trailing space. It was mix and match throughout the code which is pretty normal to see on collaborative bases like this. 
As it stands, there are 8 remaining instances of a `#` without a trailing whitespace. All of these are legit code and have remain unchanged.

 Use consistent whitespace across all comments

---

docs/man/ytfzf.5

Follows fix spelling in the manual file ytfzf.5 according to the packaging in Debian, because I am the maintainer of the package in Debian.

Fix spelling in manpage ytfzf.5

---

docs/man/ytfzf.5

Follows fix spelling in the manual file docs/man/ytfzf.5 according to the packaging in Debian, because I am the maintainer of the package in Debian.

Fix spelling in docs/man/ytfzf.5

---

ytfzf

- add the viewed date (in the end of the array by reversing with tac) on executing add_to_hist, format is "12/10/22 12:48:06 +1100"
- make it viewable in the interface (only while checking history)
- alter interface width to add space for viewed date
adapted from https://github.com/pystardust/ytfzf/pull/171/commits/a74ca6cfb2c6c893cf3cce5288b8dcb375a1a820
reminder that @pystardust might want to remove upload date altogether to make it less cluttered https://github.com/pystardust/ytfzf/pull/171#issuecomment-808858578
this is an old altered version I had lying around on my computer, seems like there is a lot that has changed since then. still working after a bit of modification. in the text interface the viewed date only shows the date and time, not the timezone but the timezone is shown in …

add viewed date support

---

ytfzf

Similar to [this commit](https://github.com/pystardust/ytfzf/commit/f600bb678341de3f0742c9758c2f7234b887488a) that resolved #646 .  Resolves the same issue for the `invidious-channel` scraper.
This is the only other instance of a jq "else if" that I could find.

fix 'else if' jq syntax for `invidious-channel` scraper

---

ytfzf

On macos, /bin/sh doesn't handle case statements in $(...) command
substitutions unless parens are properly paired up.

ytfzf: fixed syntax errors inside of command substitutions

---

ytfzf

setting `enable_hist` and/or `enable_search_hist` to `0` should prevent saving history, at least the documentation says so but it wasn't working. This PR fixes the bug.

Fix not being able to disable history

---

credits/gardockt.md
ytfzf

Trying to invoke `M` scraper (for example, with a command `ytfzf -c M :help`) results in `command not found` error, as a result of a typo in `scrape_M` function name.

Fix "multi" scraper invocation via short name

---

ytfzf

To allow a `cmd` like `ytfzf --type=channel --submenu-opts="--type=all"`
Also do not swallow the return code of the call `ytfzf :help`

Fix modifiers in scrape_invidious_channel

---

ytfzf

Closes #677
The channel urls parsed from YTFZF_SUBSCRIPTIONS_FILE where not stripped a trailing blank between URL and comment #.
For consistency refactor similiar occurrences of trimming blanks in _get_real_channel_link and for modifiers in scrape_youtube_channel and scrape_invisious_channel functions.

Subscriptions trim_blank url #677

---

ytfzf

It seems like `fzf` does not pass those env variables when invoking reload(...) shells. That leads to messing up the tabular layout when in terminal and triggering a reload because then the default values 80 and 25 are assigned, which is different (in my case) from the actual available columns and lines.
Pass `TTY_COLS` and `TTY_LINES` to the env in reload(...) invocations of `ytfzf` and fallback to those values when defining from COLUMNS and LINES.
Introduce private functions `_init_video_info_text` and `_post_video_info_text` to be consistent in all invocations of reload(...) shells.
_init_video_info_text is passed `TTY_COLS` as first param to account for difference between `interface_text` and `interface_ext`.

next_page tabular tui did not know about COLUMNS AND LINES
