README.md

I have added instruction to make it work on MacOS. Since I use both Linux and MacOS I think it might be helpful to others too. But if you have any problem with it or wish me to change what I did I understand. Thanks for the great project anyway.

Simple instruction for MacOS

---

README.md
ytfzf

I honestly don't know what the use case of this would be, I just thought it would be a cool feature.

Add random play

---

ytfzf

changed fzf:fisrt -> fzf:top

---

README.md
ytfzf

after the video ends if -sl is specified it will ask to make another search (-s alone does nothing)

search again

---

ytfzf

(hopefully this time i didn't accidentally delete the helpinfo function lol)

changed && and || to if/else for readability

---

README.md

Instead of using ~~strikethrough~~ to indicate completed items in the To-do list, consider using checkboxes. It looks more readable/clean and gets the idea through better (present a to-do list as an actual checklist).
Certainly not necessary, but  it's aesthetic you know... :sweat_smile:

Beautify To-do list

---

ytfzf

implements FZF_DEFAULT_OPTS

---

README.md
ytfzf

Changable player

---

README.md
test
ytfzf

a way to use the youtube search filter

search filter

---

ytfzf

hopefully weird commit stuff doesn't happen

commenting

---

README.md

Hello! This script is amazing, thank you for sharing it with us.
I wanted to contribute in some way but I'm not familiar enough with shell scripting to help out.
So I read over the README and corrected a few spelling mistakes, and changed a couple of sentences to make things more clear.
I hope you don't mind and thanks again for making this script!

I reviewed the README to make minor improvements

---

ytfzf

-v for ytfzf's version, --version for ytfzf + youtube-dl's version
change YTFZF_VERSION to whichever version is necessary
merge when you think is a good time

-v, --version

---

ytfzf

an option to keep the thumbnail directory

Keep thumbs

---

README.md

Added a statement corresponding to #77 in the README.

added bug fix for #77

---

ytfzf

previews can be on top, bottom, left, or right
in conf.sh put `preview_side="SIDE"`
partial fix for #94

previews on different sides

---

conf.sh
docs/conf.sh
ytfzf

documentation for each option that can be set in conf.sh

a default conf.sh

---

docs/conf.sh
ytfzf

-A will select all results,
--update-unsable, installs the latest commit from the development branch

-A, --update-unstable

---

ytfzf

on mac, the make install path is /usr/local/bin, this makes --update match that

--update location to /usr/local/bin/ on mac

---

ytfzf

* the extra commits are from merging /development to /subscriptions

Opt arg errors

---

README.md
docs/conf.sh
ytfzf

history_file, and current_file, weren't being set in config
fancy_subscriptions, enable/disable the -----------channel---------- thing

Fancy subscriptions

---

docs/conf.sh
ytfzf

very customizable thumbnail preview text

thumbnail_video_info_text

---

README.md

I made the changes but there I'd like to put the features list and the table of content list on the same line. I think my html should work but for some reason on github it doesn't render as I think It would. I don't really now much html btw so maybe in the future someone who knows a bit more can help. But I think this is still an improvement from the last version.

new additions to readme + new discord link

---

README.md
docs/INSTALL.md

I have made the changes you asked for and I also have made the installation into a one liner which i think is better

Separation

---

docs/conf.sh

bad directory path

---

README.md
docs/INSTALL.md

Running curl as sudo isn't a good idea if it can be prevented.

Improve Readme

---

README.md
docs/USAGE.md
docs/conf.sh
ytfzf

There is a way of downloading all the subscriptions that belong to a user straight from youtube as a json file.
I added a small function which reads the contents of the "subscriptions.json" (default name when downloaded) file and makes it readable for ytfzf (creates the subscriptions file basically).
Thank you for reviewing my request!
Have a great day!
P.S.: This is my first pull request and I've noticed some smaller issues but I am not sure how to fix them.

Subscriptions straight from Big Google itself

---

docs/INSTALL.md

Add FreeBSD installation instructions

---

docs/INSTALL.md

Add notify-send and shuf to the optional dependencies

---

docs/conf.sh
ytfzf

i use a very crappy way of testing when -S is passed in my .config
```sh
if [ -n "$(printf "%s" "$1" | grep "\-S")" ]; ...```
this would allow for a simple function

better options, way to do something in config when option is parsed

---

ytfzf

- removed use of eval in places where url are used

refactor: improved security, removed use of eval

---

ytfzf

add-playlist got changed to playlist-add because it doesn't add a playlist, it adds to a playlist (also in help it displayed playlist-add)

more efficient ifs

---

ytfzf

fix: -f broken with url as search

---

docs/conf.sh
ytfzf

using the json object the get the fields, instead of relying on the tsv
#265 
#266

feat: view description in thumbnail view

---

test
ytfzf

only will work if the path starts with / or .

feat: relative playlist paths

---

docs/conf.sh
ytfzf

When adding to a playlist and a url is given as the input, it will be converted to how ytfzf reads playlists and written,
this will also happen with -R

feat: url to playlist format

---

docs/conf.sh
ytfzf

feat: search again button

---

docs/USAGE.md
docs/conf.sh
ytfzf

feat: shortcuts (credit to @simonhughcom (#288)) 

---

docs/conf.sh
ytfzf

if handle_custom_shortcuts didn't exist it would exit,
return 2 now continues loop

fix: handle_shortcuts

---

docs/USAGE.md
ytfzf

feat: --detach the video player

---

ytfzf

fix: is_url not set
fix: point History/search history not enabled to stderr

fix: is_url not set, point History/search not enabled to stderr

---

ytfzf

2 fixes:
* `-md`
* `--detach -d`

fix: player options didn't work well w/ each other

---

ytfzf

fix: subs not working

---

docs/conf.sh
ytfzf

-P wont be good w/ thumbnails with this pr but it will work in master.

feat: video-limit

---

ytfzf

fix: some playlist links are 18 characters

---

ytfzf

Forgot to change the var in `menu_command`

fix: use expect_binds var in menu_command for no thumbnail

---

ytfzf

version can be changed, it's just useful to have a number.

docs: usage, YTFZF_VERSION

---

README.md
docs/INSTALL.md
ytfzf

The convention is that when you install bypassing the package manager, you install in /usr/local/bin
also proposed changes to fix #361 (update in place)
I don't know if what i did is allowed on macs

change to /usr/local/bin and update in place

---

ytfzf

improving error handling when updating

better error handling

---

ytfzf

changing format from seconds to minutes:seconds for peertube

more readable peertube duration

---

ytfzf

changing format from seconds to minutes:seconds for peertube

more readable peertube video duration format

---

docs/man/ytfzf.1
docs/man/ytfzf.5

Started writing man pages for ytfzf. Hopefully the format/styling is acceptable. More config options can be added as and when it is finalized in the rewrite.

Add man pages

---

docs/man/ytfzf.1
ytfzf

Also added the relevant options in the man page

fix: `sort` and `detach` options

---

docs/man/ytfzf.1
ytfzf

`ytfzf -cO,Y,S search`
the while loop at the bottom could also be,
```sh
for scraper in $(printf '%s' "$scrape" | tr ',' ' '); do
...
done
unset scraper
```
but that's not pure sh.

Multi scrape

---

docs/man/ytfzf.1
docs/man/ytfzf.5
ytfzf

* also adds a search prompt for when no search is given.

feat: read stdin

---

ytfzf

Seemed a little complicated to use two different functions to process the search-query

Read the search-query from stdin even without specifying '-'

---

ytfzf

Added notification popup (notify-send) to video/audio downloads to notify the user of the status of the download (successful or failed).

Notification upon download complete

---

docs/man/ytfzf.1
docs/man/ytfzf.5
ytfzf

addresses:
> There is also this notification that comes up once playback is started. It looks cool, but it would be cooler to have the name of the video on it. Or an option to disable it, since I do not want that useless info.

Refactor players

---

Makefile

Fix the issue discussed in https://github.com/pystardust/ytfzf/issues/441

Fix issue #441 for Makefile

---

docs/man/ytfzf.1
docs/man/ytfzf.5

Hi,
I found some typos in your manuals and it would be interesting to see if your mistakes can be corrected.
Thanks for your work!!!

Fix typos in manuals

---

README.md

Went to see how I could contribute and found the ultimate low hanging fruit. lol.

Remove TOC link to extinct TODO section

---

Makefile
README.md
credits/mathisto.md
ytfzf

@Euro20179 and I tagged team this. Things are now less scary and readable by humans.
I would like to add, for posterity, that the `dd` solution this is replacing, WAS BAD ASS TO THE HIGHEST DEGREE. That is all.

Improve title_str with awk magic

---

ytfzf

Makes it more obvious where the temp file comes from

Make tmp file source clearer

---

ytfzf

These are the same changes previously discussed in #627 but rebased on top of the `development` branch instead of `master`

Better kitty compatibility when displaying images

---

README.md

required >> required

---

ytfzf

fix: parameter expansion
